spring.config.activate.on-profile: prod
management:
  prometheus:
    metrics:
      export:
        enabled: true

otel.traces.exporter: otlp
otel.metrics.exporter: otlp
otel.logs.exporter: otlp
otel.exporter.otlp.endpoint: http://otel-collector:4318