version: "3.5"

networks:
  default:
    driver: bridge
    name: data
services:
  postgres:
    image: postgres:16.3
    container_name: data-postgres
    hostname: postgres
    restart: unless-stopped
    user: 999:999
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      -  pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    privileged: true
  rabbitmq:
    image: rabbitmq:4.0-rc-management
    container_name: data-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_USER=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    privileged: true

volumes:
  pgdata: