# https://hub.docker.com/r/cloudflare/cloudflared
cloudflared-version: 2024.6.0
# https://hub.docker.com/_/caddy
caddy-version: 2.8.4-alpine
# https://hub.docker.com/r/prom/prometheus/
prometheus-version: v2.45.6
# https://hub.docker.com/r/grafana/grafana
grafana-version: 9.5.20
# https://hub.docker.com/r/grafana/loki
loki-version: 2.9.8
# https://hub.docker.com/r/grafana/tempo
tempo-version: 2.4.2
# https://hub.docker.com/_/postgres
postgres-version: 16.3
# https://hub.docker.com/r/openzipkin/zipkin/
zipkin-version: 3
# https://hub.docker.com/_/rabbitmq
rabbitmq-version: 4.0-rc-management
# https://hub.docker.com/r/otel/opentelemetry-collector
otel-version: 0.104.0
# https://hub.docker.com/r/jaegertracing/all-in-one/tags
jaeger-version: 1.60.0
# https://hub.docker.com/_/elasticsearch
# https://hub.docker.com/_/logstash
# https://hub.docker.com/_/kibana
ELK-version: 8.15.0
# https://hub.docker.com/r/opensearchproject/opensearch
# https://hub.docker.com/r/opensearchproject/opensearch-dashboards
opensearch-version: 2.16.0