elasticsearch.hosts:
  - http://elasticsearch:9200
xpack.screenshotting.browser.chromium.disableSandbox: true
#devTools.enabled: false
#translations.enabled: false
#xpack.share.enabled: false
#searchConnectors.enabled: false
#screenshotMode.enabled: false
#usageCollection.enabled: false
#xpack.telemetryCollectionManager.enabled: false
#xpack.telemetryCollectionXpack.enabled: false
#taskManager.enabled: false
#kibanaUsageCollection.enabled: false
#xpack.cloud.enabled: false
#xpack.newsfeed.enabled: false
#savedObjectsFinder.enabled: false
#noDataPage.enabled: false
#monitoringCollection.enabled: false
#licensing.enabled: false
#mapsEms.enabled: false
#globalSearch.enabled: false
#globalSearchProviders.enabled: false
#features.enabled: false
#guidedOnboarding.enabled: false
#xpack.banners.enabled: false
#licenseApiGuard.enabled: false
#customBranding.enabled: false
#ftrApis.enabled: false
#fieldsMetadata.enabled: false
#fieldFormats.enabled: false
#expressions.enabled: false
#screenshotting.enabled: false
#esUiShared.enabled: false
#customIntegrations.enabled: false
#contentManagement.enabled: false
#dataViews.enabled: false
#home.enabled: false
#searchprofiler.enabled: false
#painlessLab.enabled: false
#management.enabled: false
#spaces.enabled: false
#security.enabled: false
#telemetry.enabled: false
#licenseManagement.enabled: false
#snapshotRestore.enabled: false
#lists.enabled: false
#files.enabled: false
#encryptedSavedObjects.enabled: false
#entityManager.enabled: false
#eventLog.enabled: false
#actions.enabled: false
#observabilityAIAssistant.enabled: false
#investigate.enabled: false
#notifications.enabled: false
#cloudDataMigration.enabled: false
#aiAssistantManagementSelection.enabled: false
#advancedSettings.enabled: false
#grokdebugger.enabled: false
#console.enabled: false
#searchNotebooks.enabled: false
#searchHomepage.enabled: false
##bfetch.enabled: false
#data.enabled: false
#savedObjectsTagging.enabled: false
#savedObjectsManagement.enabled: false
#unifiedSearch.enabled: false
#navigation.enabled: false
#graph.enabled: false
#embeddable.enabled: false
#uiActionsEnhanced.enabled: false
#savedSearch.enabled: false
#presentationUtil.enabled: false
#expressionShape.enabled: false
#expressionRevealImage.enabled: false
#expressionRepeatImage.enabled: false
#expressionMetric.enabled: false
#expressionImage.enabled: false
#controls.enabled: false
#alerting.enabled: false
#logsDataAccess.enabled: false
#fileUpload.enabled: false
#ingestPipelines.enabled: false
#ecsDataQualityDashboard.enabled: false
#dataViewFieldEditor.enabled: false
#dataViewManagement.enabled: false
#charts.enabled: false
#watcher.enabled: false
#visualizations.enabled: false
#visTypeXy.enabled: false
#visTypeVislib.enabled: false
#visTypeVega.enabled: false
#visTypeTimeseries.enabled: false
#visTypeTimelion.enabled: false
#visTypeTagcloud.enabled: false
#visTypeTable.enabled: false
#visTypeMetric.enabled: false
#visTypeMarkdown.enabled: false
#visTypeHeatmap.enabled: false
#inputControlVis.enabled: false
#expressionTagcloud.enabled: false
#expressionPartitionVis.enabled: false
#visTypePie.enabled: false
#expressionMetricVis.enabled: false
#expressionLegacyMetricVis.enabled: false
#expressionHeatmap.enabled: false
#expressionGauge.enabled: false
#visTypeGauge.enabled: false
#eventAnnotation.enabled: false
#expressionXY.enabled: false
#lens.enabled: false
#maps.enabled: false
#dataVisualizer.enabled: false
#dashboard.enabled: false
#triggersActionsUi.enabled: false
#transform.enabled: false
#stackConnectors.enabled: false
#searchPlayground.enabled: false
#integrationAssistant.enabled: false
#stackAlerts.enabled: false
#ruleRegistry.enabled: false
#cases.enabled: false
#timelines.enabled: false
#sessionView.enabled: false
#kubernetesSecurity.enabled: false
#threatIntelligence.enabled: false
#metricsDataAccess.enabled: false
#logsShared.enabled: false
##aiops.enabled: false
#discover.enabled: false
#reporting.enabled: false
#canvas.enabled: false
#ml.enabled: false
#searchInferenceEndpoints.enabled: false
#elasticAssistant.enabled: false
#logsExplorer.enabled: false
#fleet.enabled: false
#osquery.enabled: false
#indexManagement.enabled: false
#textBasedLanguages.enabled: false
#rollup.enabled: false
#remoteClusters.enabled: false
#crossClusterReplication.enabled: false
#indexLifecycleManagement.enabled: false
#enterpriseSearch.enabled: false
#observabilityAiAssistantManagement.enabled: false
#datasetQuality.enabled: false
#dataQuality.enabled: false
#cloudSecurityPosture.enabled: false
#cloudDefend.enabled: false
#securitySolution.enabled: false
#securitySolutionEss.enabled: false
#observability.enabled: false
#uptime.enabled: false
#synthetics.enabled: false
#slo.enabled: false
#observabilityLogsExplorer.enabled: false
#observabilityOnboarding.enabled: false
#observabilityAIAssistantApp.enabled: false
#discoverEnhanced.enabled: false
#links.enabled: false
#dashboardEnhanced.enabled: false
#apmDataAccess.enabled: false
#infra.enabled: false
#upgradeAssistant.enabled: false
#monitoring.enabled: false
#logstash.enabled: false
#apm.enabled: false
#ux.enabled: false
#assetsDataAccess.enabled: false